// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/distrieats.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CrearPedidoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClienteId     string                 `protobuf:"bytes,2,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	PedidoId      string                 `protobuf:"bytes,3,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearPedidoRequest) Reset() {
	*x = CrearPedidoRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearPedidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearPedidoRequest) ProtoMessage() {}

func (x *CrearPedidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearPedidoRequest.ProtoReflect.Descriptor instead.
func (*CrearPedidoRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{0}
}

func (x *CrearPedidoRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CrearPedidoRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *CrearPedidoRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

type CrearPedidoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	DatanodeId    string                 `protobuf:"bytes,3,opt,name=datanode_id,json=datanodeId,proto3" json:"datanode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearPedidoResponse) Reset() {
	*x = CrearPedidoResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearPedidoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearPedidoResponse) ProtoMessage() {}

func (x *CrearPedidoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearPedidoResponse.ProtoReflect.Descriptor instead.
func (*CrearPedidoResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{1}
}

func (x *CrearPedidoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CrearPedidoResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *CrearPedidoResponse) GetDatanodeId() string {
	if x != nil {
		return x.DatanodeId
	}
	return ""
}

type ConsultarEstadoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     string                 `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	PedidoId      string                 `protobuf:"bytes,2,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarEstadoRequest) Reset() {
	*x = ConsultarEstadoRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarEstadoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEstadoRequest) ProtoMessage() {}

func (x *ConsultarEstadoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEstadoRequest.ProtoReflect.Descriptor instead.
func (*ConsultarEstadoRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{2}
}

func (x *ConsultarEstadoRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *ConsultarEstadoRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

type ConsultarEstadoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PedidoId      string                 `protobuf:"bytes,1,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	Estado        string                 `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarEstadoResponse) Reset() {
	*x = ConsultarEstadoResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarEstadoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEstadoResponse) ProtoMessage() {}

func (x *ConsultarEstadoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEstadoResponse.ProtoReflect.Descriptor instead.
func (*ConsultarEstadoResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{3}
}

func (x *ConsultarEstadoResponse) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

func (x *ConsultarEstadoResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type UpdateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PedidoId      string                 `protobuf:"bytes,1,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	Estado        string                 `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
	VectorClock   map[string]int32       `protobuf:"bytes,3,rep,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOrderRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

func (x *UpdateOrderRequest) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *UpdateOrderRequest) GetVectorClock() map[string]int32 {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type UpdateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderResponse) Reset() {
	*x = UpdateOrderResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderResponse) ProtoMessage() {}

func (x *UpdateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PedidoData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estado        string                 `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	VectorClock   map[string]int32       `protobuf:"bytes,2,rep,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PedidoData) Reset() {
	*x = PedidoData{}
	mi := &file_proto_distrieats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PedidoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedidoData) ProtoMessage() {}

func (x *PedidoData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedidoData.ProtoReflect.Descriptor instead.
func (*PedidoData) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{6}
}

func (x *PedidoData) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *PedidoData) GetVectorClock() map[string]int32 {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type GossipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrigenNodeId  string                 `protobuf:"bytes,1,opt,name=origen_node_id,json=origenNodeId,proto3" json:"origen_node_id,omitempty"`
	EstadoPedidos map[string]*PedidoData `protobuf:"bytes,2,rep,name=estado_pedidos,json=estadoPedidos,proto3" json:"estado_pedidos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{7}
}

func (x *GossipRequest) GetOrigenNodeId() string {
	if x != nil {
		return x.OrigenNodeId
	}
	return ""
}

func (x *GossipRequest) GetEstadoPedidos() map[string]*PedidoData {
	if x != nil {
		return x.EstadoPedidos
	}
	return nil
}

type GossipResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PedidosActualizados map[string]*PedidoData `protobuf:"bytes,2,rep,name=pedidos_actualizados,json=pedidosActualizados,proto3" json:"pedidos_actualizados,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{8}
}

func (x *GossipResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GossipResponse) GetPedidosActualizados() map[string]*PedidoData {
	if x != nil {
		return x.PedidosActualizados
	}
	return nil
}

var File_proto_distrieats_proto protoreflect.FileDescriptor

const file_proto_distrieats_proto_rawDesc = "" +
	"\n" +
	"\x16proto/distrieats.proto\x12\n" +
	"distrieats\"o\n" +
	"\x12CrearPedidoRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x02 \x01(\tR\tclienteId\x12\x1b\n" +
	"\tpedido_id\x18\x03 \x01(\tR\bpedidoId\"j\n" +
	"\x13CrearPedidoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12\x1f\n" +
	"\vdatanode_id\x18\x03 \x01(\tR\n" +
	"datanodeId\"T\n" +
	"\x16ConsultarEstadoRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\tR\tclienteId\x12\x1b\n" +
	"\tpedido_id\x18\x02 \x01(\tR\bpedidoId\"N\n" +
	"\x17ConsultarEstadoResponse\x12\x1b\n" +
	"\tpedido_id\x18\x01 \x01(\tR\bpedidoId\x12\x16\n" +
	"\x06estado\x18\x02 \x01(\tR\x06estado\"\xdd\x01\n" +
	"\x12UpdateOrderRequest\x12\x1b\n" +
	"\tpedido_id\x18\x01 \x01(\tR\bpedidoId\x12\x16\n" +
	"\x06estado\x18\x02 \x01(\tR\x06estado\x12R\n" +
	"\fvector_clock\x18\x03 \x03(\v2/.distrieats.UpdateOrderRequest.VectorClockEntryR\vvectorClock\x1a>\n" +
	"\x10VectorClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"/\n" +
	"\x13UpdateOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb0\x01\n" +
	"\n" +
	"PedidoData\x12\x16\n" +
	"\x06estado\x18\x01 \x01(\tR\x06estado\x12J\n" +
	"\fvector_clock\x18\x02 \x03(\v2'.distrieats.PedidoData.VectorClockEntryR\vvectorClock\x1a>\n" +
	"\x10VectorClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xe4\x01\n" +
	"\rGossipRequest\x12$\n" +
	"\x0eorigen_node_id\x18\x01 \x01(\tR\forigenNodeId\x12S\n" +
	"\x0eestado_pedidos\x18\x02 \x03(\v2,.distrieats.GossipRequest.EstadoPedidosEntryR\restadoPedidos\x1aX\n" +
	"\x12EstadoPedidosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.distrieats.PedidoDataR\x05value:\x028\x01\"\xf2\x01\n" +
	"\x0eGossipResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12f\n" +
	"\x14pedidos_actualizados\x18\x02 \x03(\v23.distrieats.GossipResponse.PedidosActualizadosEntryR\x13pedidosActualizados\x1a^\n" +
	"\x18PedidosActualizadosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.distrieats.PedidoDataR\x05value:\x028\x012\x92\x02\n" +
	"\fOrderGateway\x12N\n" +
	"\vCrearPedido\x12\x1e.distrieats.CrearPedidoRequest\x1a\x1f.distrieats.CrearPedidoResponse\x12Z\n" +
	"\x0fConsultarEstado\x12\".distrieats.ConsultarEstadoRequest\x1a#.distrieats.ConsultarEstadoResponse\x12V\n" +
	"\x13EnviarActualizacion\x12\x1e.distrieats.UpdateOrderRequest\x1a\x1f.distrieats.UpdateOrderResponse2\xd2\x02\n" +
	"\x0fDatanodeService\x12N\n" +
	"\vUpdateOrder\x12\x1e.distrieats.UpdateOrderRequest\x1a\x1f.distrieats.UpdateOrderResponse\x12Z\n" +
	"\x0fConsultarEstado\x12\".distrieats.ConsultarEstadoRequest\x1a#.distrieats.ConsultarEstadoResponse\x12C\n" +
	"\n" +
	"GossipSync\x12\x19.distrieats.GossipRequest\x1a\x1a.distrieats.GossipResponse\x12N\n" +
	"\vCrearPedido\x12\x1e.distrieats.CrearPedidoRequest\x1a\x1f.distrieats.CrearPedidoResponseB\x12Z\x10distrieats/protob\x06proto3"

var (
	file_proto_distrieats_proto_rawDescOnce sync.Once
	file_proto_distrieats_proto_rawDescData []byte
)

func file_proto_distrieats_proto_rawDescGZIP() []byte {
	file_proto_distrieats_proto_rawDescOnce.Do(func() {
		file_proto_distrieats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_distrieats_proto_rawDesc), len(file_proto_distrieats_proto_rawDesc)))
	})
	return file_proto_distrieats_proto_rawDescData
}

var file_proto_distrieats_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_distrieats_proto_goTypes = []any{
	(*CrearPedidoRequest)(nil),      // 0: distrieats.CrearPedidoRequest
	(*CrearPedidoResponse)(nil),     // 1: distrieats.CrearPedidoResponse
	(*ConsultarEstadoRequest)(nil),  // 2: distrieats.ConsultarEstadoRequest
	(*ConsultarEstadoResponse)(nil), // 3: distrieats.ConsultarEstadoResponse
	(*UpdateOrderRequest)(nil),      // 4: distrieats.UpdateOrderRequest
	(*UpdateOrderResponse)(nil),     // 5: distrieats.UpdateOrderResponse
	(*PedidoData)(nil),              // 6: distrieats.PedidoData
	(*GossipRequest)(nil),           // 7: distrieats.GossipRequest
	(*GossipResponse)(nil),          // 8: distrieats.GossipResponse
	nil,                             // 9: distrieats.UpdateOrderRequest.VectorClockEntry
	nil,                             // 10: distrieats.PedidoData.VectorClockEntry
	nil,                             // 11: distrieats.GossipRequest.EstadoPedidosEntry
	nil,                             // 12: distrieats.GossipResponse.PedidosActualizadosEntry
}
var file_proto_distrieats_proto_depIdxs = []int32{
	9,  // 0: distrieats.UpdateOrderRequest.vector_clock:type_name -> distrieats.UpdateOrderRequest.VectorClockEntry
	10, // 1: distrieats.PedidoData.vector_clock:type_name -> distrieats.PedidoData.VectorClockEntry
	11, // 2: distrieats.GossipRequest.estado_pedidos:type_name -> distrieats.GossipRequest.EstadoPedidosEntry
	12, // 3: distrieats.GossipResponse.pedidos_actualizados:type_name -> distrieats.GossipResponse.PedidosActualizadosEntry
	6,  // 4: distrieats.GossipRequest.EstadoPedidosEntry.value:type_name -> distrieats.PedidoData
	6,  // 5: distrieats.GossipResponse.PedidosActualizadosEntry.value:type_name -> distrieats.PedidoData
	0,  // 6: distrieats.OrderGateway.CrearPedido:input_type -> distrieats.CrearPedidoRequest
	2,  // 7: distrieats.OrderGateway.ConsultarEstado:input_type -> distrieats.ConsultarEstadoRequest
	4,  // 8: distrieats.OrderGateway.EnviarActualizacion:input_type -> distrieats.UpdateOrderRequest
	4,  // 9: distrieats.DatanodeService.UpdateOrder:input_type -> distrieats.UpdateOrderRequest
	2,  // 10: distrieats.DatanodeService.ConsultarEstado:input_type -> distrieats.ConsultarEstadoRequest
	7,  // 11: distrieats.DatanodeService.GossipSync:input_type -> distrieats.GossipRequest
	0,  // 12: distrieats.DatanodeService.CrearPedido:input_type -> distrieats.CrearPedidoRequest
	1,  // 13: distrieats.OrderGateway.CrearPedido:output_type -> distrieats.CrearPedidoResponse
	3,  // 14: distrieats.OrderGateway.ConsultarEstado:output_type -> distrieats.ConsultarEstadoResponse
	5,  // 15: distrieats.OrderGateway.EnviarActualizacion:output_type -> distrieats.UpdateOrderResponse
	5,  // 16: distrieats.DatanodeService.UpdateOrder:output_type -> distrieats.UpdateOrderResponse
	3,  // 17: distrieats.DatanodeService.ConsultarEstado:output_type -> distrieats.ConsultarEstadoResponse
	8,  // 18: distrieats.DatanodeService.GossipSync:output_type -> distrieats.GossipResponse
	1,  // 19: distrieats.DatanodeService.CrearPedido:output_type -> distrieats.CrearPedidoResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_distrieats_proto_init() }
func file_proto_distrieats_proto_init() {
	if File_proto_distrieats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_distrieats_proto_rawDesc), len(file_proto_distrieats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_distrieats_proto_goTypes,
		DependencyIndexes: file_proto_distrieats_proto_depIdxs,
		MessageInfos:      file_proto_distrieats_proto_msgTypes,
	}.Build()
	File_proto_distrieats_proto = out.File
	file_proto_distrieats_proto_goTypes = nil
	file_proto_distrieats_proto_depIdxs = nil
}
