// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/distrieats.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderGateway_CrearPedido_FullMethodName         = "/distrieats.OrderGateway/CrearPedido"
	OrderGateway_ConsultarEstado_FullMethodName     = "/distrieats.OrderGateway/ConsultarEstado"
	OrderGateway_EnviarActualizacion_FullMethodName = "/distrieats.OrderGateway/EnviarActualizacion"
	OrderGateway_ReportarTermino_FullMethodName     = "/distrieats.OrderGateway/ReportarTermino"
	OrderGateway_ReportarRYW_FullMethodName         = "/distrieats.OrderGateway/ReportarRYW"
)

// OrderGatewayClient is the client API for OrderGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderGatewayClient interface {
	CrearPedido(ctx context.Context, in *CrearPedidoRequest, opts ...grpc.CallOption) (*CrearPedidoResponse, error)
	ConsultarEstado(ctx context.Context, in *ConsultarEstadoRequest, opts ...grpc.CallOption) (*ConsultarEstadoResponse, error)
	EnviarActualizacion(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*UpdateOrderResponse, error)
	ReportarTermino(ctx context.Context, in *ClientDoneRequest, opts ...grpc.CallOption) (*ClientDoneResponse, error)
	ReportarRYW(ctx context.Context, in *RYWRequest, opts ...grpc.CallOption) (*RYWResponse, error)
}

type orderGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderGatewayClient(cc grpc.ClientConnInterface) OrderGatewayClient {
	return &orderGatewayClient{cc}
}

func (c *orderGatewayClient) CrearPedido(ctx context.Context, in *CrearPedidoRequest, opts ...grpc.CallOption) (*CrearPedidoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrearPedidoResponse)
	err := c.cc.Invoke(ctx, OrderGateway_CrearPedido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderGatewayClient) ConsultarEstado(ctx context.Context, in *ConsultarEstadoRequest, opts ...grpc.CallOption) (*ConsultarEstadoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarEstadoResponse)
	err := c.cc.Invoke(ctx, OrderGateway_ConsultarEstado_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderGatewayClient) EnviarActualizacion(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*UpdateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrderResponse)
	err := c.cc.Invoke(ctx, OrderGateway_EnviarActualizacion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderGatewayClient) ReportarTermino(ctx context.Context, in *ClientDoneRequest, opts ...grpc.CallOption) (*ClientDoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientDoneResponse)
	err := c.cc.Invoke(ctx, OrderGateway_ReportarTermino_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderGatewayClient) ReportarRYW(ctx context.Context, in *RYWRequest, opts ...grpc.CallOption) (*RYWResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RYWResponse)
	err := c.cc.Invoke(ctx, OrderGateway_ReportarRYW_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderGatewayServer is the server API for OrderGateway service.
// All implementations must embed UnimplementedOrderGatewayServer
// for forward compatibility.
type OrderGatewayServer interface {
	CrearPedido(context.Context, *CrearPedidoRequest) (*CrearPedidoResponse, error)
	ConsultarEstado(context.Context, *ConsultarEstadoRequest) (*ConsultarEstadoResponse, error)
	EnviarActualizacion(context.Context, *UpdateOrderRequest) (*UpdateOrderResponse, error)
	ReportarTermino(context.Context, *ClientDoneRequest) (*ClientDoneResponse, error)
	ReportarRYW(context.Context, *RYWRequest) (*RYWResponse, error)
	mustEmbedUnimplementedOrderGatewayServer()
}

// UnimplementedOrderGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderGatewayServer struct{}

func (UnimplementedOrderGatewayServer) CrearPedido(context.Context, *CrearPedidoRequest) (*CrearPedidoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearPedido not implemented")
}
func (UnimplementedOrderGatewayServer) ConsultarEstado(context.Context, *ConsultarEstadoRequest) (*ConsultarEstadoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarEstado not implemented")
}
func (UnimplementedOrderGatewayServer) EnviarActualizacion(context.Context, *UpdateOrderRequest) (*UpdateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnviarActualizacion not implemented")
}
func (UnimplementedOrderGatewayServer) ReportarTermino(context.Context, *ClientDoneRequest) (*ClientDoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportarTermino not implemented")
}
func (UnimplementedOrderGatewayServer) ReportarRYW(context.Context, *RYWRequest) (*RYWResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportarRYW not implemented")
}
func (UnimplementedOrderGatewayServer) mustEmbedUnimplementedOrderGatewayServer() {}
func (UnimplementedOrderGatewayServer) testEmbeddedByValue()                      {}

// UnsafeOrderGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderGatewayServer will
// result in compilation errors.
type UnsafeOrderGatewayServer interface {
	mustEmbedUnimplementedOrderGatewayServer()
}

func RegisterOrderGatewayServer(s grpc.ServiceRegistrar, srv OrderGatewayServer) {
	// If the following call panics, it indicates UnimplementedOrderGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderGateway_ServiceDesc, srv)
}

func _OrderGateway_CrearPedido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearPedidoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderGatewayServer).CrearPedido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderGateway_CrearPedido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderGatewayServer).CrearPedido(ctx, req.(*CrearPedidoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderGateway_ConsultarEstado_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarEstadoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderGatewayServer).ConsultarEstado(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderGateway_ConsultarEstado_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderGatewayServer).ConsultarEstado(ctx, req.(*ConsultarEstadoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderGateway_EnviarActualizacion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderGatewayServer).EnviarActualizacion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderGateway_EnviarActualizacion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderGatewayServer).EnviarActualizacion(ctx, req.(*UpdateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderGateway_ReportarTermino_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientDoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderGatewayServer).ReportarTermino(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderGateway_ReportarTermino_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderGatewayServer).ReportarTermino(ctx, req.(*ClientDoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderGateway_ReportarRYW_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RYWRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderGatewayServer).ReportarRYW(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderGateway_ReportarRYW_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderGatewayServer).ReportarRYW(ctx, req.(*RYWRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderGateway_ServiceDesc is the grpc.ServiceDesc for OrderGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distrieats.OrderGateway",
	HandlerType: (*OrderGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrearPedido",
			Handler:    _OrderGateway_CrearPedido_Handler,
		},
		{
			MethodName: "ConsultarEstado",
			Handler:    _OrderGateway_ConsultarEstado_Handler,
		},
		{
			MethodName: "EnviarActualizacion",
			Handler:    _OrderGateway_EnviarActualizacion_Handler,
		},
		{
			MethodName: "ReportarTermino",
			Handler:    _OrderGateway_ReportarTermino_Handler,
		},
		{
			MethodName: "ReportarRYW",
			Handler:    _OrderGateway_ReportarRYW_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/distrieats.proto",
}

const (
	DatanodeService_UpdateOrder_FullMethodName       = "/distrieats.DatanodeService/UpdateOrder"
	DatanodeService_ConsultarEstado_FullMethodName   = "/distrieats.DatanodeService/ConsultarEstado"
	DatanodeService_GossipSync_FullMethodName        = "/distrieats.DatanodeService/GossipSync"
	DatanodeService_CrearPedido_FullMethodName       = "/distrieats.DatanodeService/CrearPedido"
	DatanodeService_SignalGracePeriod_FullMethodName = "/distrieats.DatanodeService/SignalGracePeriod"
	DatanodeService_GetFinalState_FullMethodName     = "/distrieats.DatanodeService/GetFinalState"
)

// DatanodeServiceClient is the client API for DatanodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatanodeServiceClient interface {
	UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*UpdateOrderResponse, error)
	ConsultarEstado(ctx context.Context, in *ConsultarEstadoRequest, opts ...grpc.CallOption) (*ConsultarEstadoResponse, error)
	GossipSync(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*GossipResponse, error)
	CrearPedido(ctx context.Context, in *CrearPedidoRequest, opts ...grpc.CallOption) (*CrearPedidoResponse, error)
	SignalGracePeriod(ctx context.Context, in *GraceRequest, opts ...grpc.CallOption) (*GraceResponse, error)
	GetFinalState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
}

type datanodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatanodeServiceClient(cc grpc.ClientConnInterface) DatanodeServiceClient {
	return &datanodeServiceClient{cc}
}

func (c *datanodeServiceClient) UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*UpdateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrderResponse)
	err := c.cc.Invoke(ctx, DatanodeService_UpdateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) ConsultarEstado(ctx context.Context, in *ConsultarEstadoRequest, opts ...grpc.CallOption) (*ConsultarEstadoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarEstadoResponse)
	err := c.cc.Invoke(ctx, DatanodeService_ConsultarEstado_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) GossipSync(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*GossipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GossipResponse)
	err := c.cc.Invoke(ctx, DatanodeService_GossipSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) CrearPedido(ctx context.Context, in *CrearPedidoRequest, opts ...grpc.CallOption) (*CrearPedidoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrearPedidoResponse)
	err := c.cc.Invoke(ctx, DatanodeService_CrearPedido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) SignalGracePeriod(ctx context.Context, in *GraceRequest, opts ...grpc.CallOption) (*GraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraceResponse)
	err := c.cc.Invoke(ctx, DatanodeService_SignalGracePeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) GetFinalState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateResponse)
	err := c.cc.Invoke(ctx, DatanodeService_GetFinalState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatanodeServiceServer is the server API for DatanodeService service.
// All implementations must embed UnimplementedDatanodeServiceServer
// for forward compatibility.
type DatanodeServiceServer interface {
	UpdateOrder(context.Context, *UpdateOrderRequest) (*UpdateOrderResponse, error)
	ConsultarEstado(context.Context, *ConsultarEstadoRequest) (*ConsultarEstadoResponse, error)
	GossipSync(context.Context, *GossipRequest) (*GossipResponse, error)
	CrearPedido(context.Context, *CrearPedidoRequest) (*CrearPedidoResponse, error)
	SignalGracePeriod(context.Context, *GraceRequest) (*GraceResponse, error)
	GetFinalState(context.Context, *StateRequest) (*StateResponse, error)
	mustEmbedUnimplementedDatanodeServiceServer()
}

// UnimplementedDatanodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatanodeServiceServer struct{}

func (UnimplementedDatanodeServiceServer) UpdateOrder(context.Context, *UpdateOrderRequest) (*UpdateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrder not implemented")
}
func (UnimplementedDatanodeServiceServer) ConsultarEstado(context.Context, *ConsultarEstadoRequest) (*ConsultarEstadoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarEstado not implemented")
}
func (UnimplementedDatanodeServiceServer) GossipSync(context.Context, *GossipRequest) (*GossipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GossipSync not implemented")
}
func (UnimplementedDatanodeServiceServer) CrearPedido(context.Context, *CrearPedidoRequest) (*CrearPedidoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearPedido not implemented")
}
func (UnimplementedDatanodeServiceServer) SignalGracePeriod(context.Context, *GraceRequest) (*GraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignalGracePeriod not implemented")
}
func (UnimplementedDatanodeServiceServer) GetFinalState(context.Context, *StateRequest) (*StateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFinalState not implemented")
}
func (UnimplementedDatanodeServiceServer) mustEmbedUnimplementedDatanodeServiceServer() {}
func (UnimplementedDatanodeServiceServer) testEmbeddedByValue()                         {}

// UnsafeDatanodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatanodeServiceServer will
// result in compilation errors.
type UnsafeDatanodeServiceServer interface {
	mustEmbedUnimplementedDatanodeServiceServer()
}

func RegisterDatanodeServiceServer(s grpc.ServiceRegistrar, srv DatanodeServiceServer) {
	// If the following call panics, it indicates UnimplementedDatanodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatanodeService_ServiceDesc, srv)
}

func _DatanodeService_UpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).UpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_UpdateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).UpdateOrder(ctx, req.(*UpdateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_ConsultarEstado_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarEstadoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).ConsultarEstado(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_ConsultarEstado_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).ConsultarEstado(ctx, req.(*ConsultarEstadoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_GossipSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).GossipSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_GossipSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).GossipSync(ctx, req.(*GossipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_CrearPedido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearPedidoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).CrearPedido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_CrearPedido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).CrearPedido(ctx, req.(*CrearPedidoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_SignalGracePeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).SignalGracePeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_SignalGracePeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).SignalGracePeriod(ctx, req.(*GraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_GetFinalState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).GetFinalState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_GetFinalState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).GetFinalState(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatanodeService_ServiceDesc is the grpc.ServiceDesc for DatanodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatanodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distrieats.DatanodeService",
	HandlerType: (*DatanodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateOrder",
			Handler:    _DatanodeService_UpdateOrder_Handler,
		},
		{
			MethodName: "ConsultarEstado",
			Handler:    _DatanodeService_ConsultarEstado_Handler,
		},
		{
			MethodName: "GossipSync",
			Handler:    _DatanodeService_GossipSync_Handler,
		},
		{
			MethodName: "CrearPedido",
			Handler:    _DatanodeService_CrearPedido_Handler,
		},
		{
			MethodName: "SignalGracePeriod",
			Handler:    _DatanodeService_SignalGracePeriod_Handler,
		},
		{
			MethodName: "GetFinalState",
			Handler:    _DatanodeService_GetFinalState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/distrieats.proto",
}
